### ISSUE TITLE
Compile crash

### ISSUE THREAD

**Issue by dslackw** [worldforge/ember#20]
I try compile ember on Slackware64 -current:

http://pastebin.com/kZahe6AR

**Comment by erikogenvik** [comment]
I've pushed a fix for at least the first reported issue in 128cb3a8e35d395461fb03165e2fb6425bdabd31
I'm guessing that it should resolve the others as well. Could you check?

**Comment by dslackw** [comment]
Fixed !!! Thank you very much!
