### ISSUE TITLE
ember 0.7.2 fails to build with gcc9 (debian / fedora)

### ISSUE THREAD

**Issue by rosset** [worldforge/ember#25]
https://bugzilla.redhat.com/show_bug.cgi?id=1674851

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=925674

Atlas.cxx: In function 'int tolua_Atlas_Atlas_Message_MapType_iterator__eq00(lua_State*)':
Atlas.cxx:1911:43: error: 'std::map<std::__cxx11::basic_string<char>, Atlas::Message::Element>::iterator' {aka 'struct std::_Rb_tree_iterator<std::pair<const std::__cxx11::basic_string<char>, Atlas::Message::Element> >'} has no member named 'operator=='; did you mean 'operator*'?
 1911 |    bool tolua_ret = (bool)  self->operator==(*value);
      |                                           ^~
      |                                           operator*
make[6]: *** [Makefile:435: Atlas.o] Error 1

**Comment by erikogenvik** [comment]
The package in Fedora is unfortunately outdated, and the project is not stable enough currently. I would recommend removing it from Fedora and waiting until we're at a more stable situation where we don't foresee any more larger protocol and API changes.
