### ISSUE TITLE
OGRE must be built with thread support

### ISSUE THREAD

**Issue by DSorlov** [worldforge/ember#26]
Using Ubuntu 18.04 on Azure to build
Have followed instructions and installed all supporting libraries. Have defeated most errors that have been thrown so far however not able to get passed this error right now 

`./hammer.sh build ember`

results in

```
/home/daniel/hammer/work/source/worldforge/clients/ember/src/components/ogre/OgreSetup.cpp:52:2: error: #error OGRE must be built with thread support.
 #error OGRE must be built with thread support.
  ^~~~~
```

**Comment by erikogenvik** [comment]
Do you have a system provided OGRE installation? I'm guessing that the build script pulls in another installation than the one built by Hammer.

**Comment by DSorlov** [comment]
Ok! Solved. It actually failed due to a silent build error in OGRE that made it go bananas.
