### ISSUE TITLE
ember latest download for windows returns 403

### ISSUE THREAD

**Issue by animation303** [worldforge/ember#33]
http://amber.worldforge.org/ember/releases/unstable/Ember-latest.exe is forbidden, not a problem to build from source, but I thought I should bring it up somewhere

**Comment by erikogenvik** [comment]
Thanks for reporting this, it should be fixed now.

**Comment by echads** [comment]
Seems to be happening again.

**Comment by echads** [comment]
Waited a few days and then download worked. Perhaps it's a hit or miss automation issue with the releases?

**Comment by erikogenvik** [comment]
It's related to a bug in rsync that's causing an error when setting permissions. A more proper fix would be to rebuild rsync on the machine in question.
