### ISSUE TITLE
Crash when killed

### ISSUE THREAD

**Issue by NetSysFire** [worldforge/ember#36]
Steps to reproduce:

1. Connect to any server. In this case I got my local instance of cyphesis.
2. Get killed by wolves or goblins or so.
3. Segfault. Trace attached. Because of conan conflicts I can not rebuild ember, so the trace will be of limited use since I could not recompile with debugging symbols enabled.

[Trace](https://github.com/worldforge/ember/files/9136864/ember.txt)

System info:

- OS: Arch Linux
- Ember version: 05d49f7f8

**Comment by erikogenvik** [comment]
This has been fixed by this commit: https://github.com/worldforge/eris/commit/0229c7f68753bce94bb8581518beee7d50341038
