### ISSUE TITLE
Build on Ubuntu 20.04

### ISSUE THREAD

**Issue by Demodian** [worldforge/ember#38]
Using the hammer.sh process for building, the install-deps installed OGRE 13.4.1, so when it got to ember, it did this:

  Ember client...
  Configuring...
CMake Error at CMakeLists.txt:258 (find_package):
  Could not find a configuration file for package "OGRE" that is compatible
  with requested version "13.4.2".

  The following configuration files were considered but not accepted:

    .../src/worldforge/hammer/work/local/lib/OGRE/cmake/OGREConfig.cmake, version: 13.4.1

This is from a clean build from tonight.

**Comment by erikogenvik** [comment]
Thanks for reporting, this has now been fixed. Just update Hammer to the latest version and it should work.
