### ISSUE TITLE
Depth of Field is misbehaving

### ISSUE THREAD

**Issue by NetSysFire** [worldforge/ember#39]
Many textures are blurry for no reason. I assume this depth of field thing is for performance reasons but it appears there is no way to change this behavior.

![image](https://user-images.githubusercontent.com/59517351/206917626-0fca2a15-caaf-449e-a35a-09c72ad03649.png)

The texture is perfectly sharp when you look at it with an angle of about 90°.

![image](https://user-images.githubusercontent.com/59517351/206917641-bc8e4d8c-08e9-43be-bf89-d98338f1e2ac.png)

Expected behavior:

The textures which are close to you are not blurry and this effect is not nearly as obvious.

**Comment by erikogenvik** [comment]
Fixed in 3f4274c1c416b3b5cfb464b8dcb8de2bd845badd
